export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const MORE_CATEGORIES_AVAILABLE   = 'MORE_CATEGORIES_AVAILABLE';

export const ZERO_CATEGORIES = 'ZERO_CATEGORIES'

export const LAST_VISIBLE_CATEGORY_ID = 'LAST_VISIBLE_CATEGORY_ID'
