export const FETCH_ARTICLE_REQUEST = 'FETCH_ARTICLE_REQUEST';

export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS';

export const FETCH_ARTICLE_FAILURE = 'FETCH_ARTICLE_FAILURE';

export const CLEAR_ARTICLE = 'CLEAR_ARTICLE';

export const SHOW_LOGIN_POPUP='SHOW_LOGIN_POPUP';

export const HIDE_LOGIN_POPUP='HIDE_LOGIN_POPUP';

export const SHOW_RECAPTCHA_POPUP='SHOW_RECAPTCHA_POPUP';

export const HIDE_RECAPTCHA_POPUP='HIDE_RECAPTCHA_POPUP';

export const SET_TYPE_OF_TASK='SET_TYPE_OF_TASK';

export const SET_COMMENT='SET_COMMENT';

export const SET_ARTICLE_SEO='SET_ARTICLE_SEO';

export const PERFORM_TASK='PERFORM_TASK'; 

export const LOGIN_AND_PERFORM_TASK_REQUEST='LOGIN_AND_PERFORM_TASK_REQUEST';
export const LOGIN_AND_PERFORM_TASK_SUCCESS='LOGIN_AND_PERFORM_TASK_SUCCESS';
export const LOGIN_AND_PERFORM_TASK_FAILURE='LOGIN_AND_PERFORM_TASK_FAILURE';

export const CHECK_VOTE_STATUS_REQUEST='CHECK_VOTE_STATUS_REQUEST';
export const CHECK_VOTE_STATUS_SUCCESS='CHECK_VOTE_STATUS_SUCCESS';

export const UPDATE_VOTE_COLOR='UPDATE_VOTE_COLOR'