export const FETCH_PERMISSIONS_REQUEST = 'FETCH_PERMISSIONS_REQUEST';
export const FETCH_PERMISSIONS_SUCCESS = 'FETCH_PERMISSIONS_SUCCESS';
export const FETCH_PERMISSIONS_FAILURE = 'FETCH_PERMISSIONS_FAILURE';

export const SHOW_NOTIFICATION_LIST ="SHOW_NOTIFICATION_LIST";
export const HIDE_NOTIFICATION_LIST ="HIDE_NOTIFICATION_LIST";

export const SHOW_PROFILE_PAGE ="SHOW_PROFILE_PAGE";
export const HIDE_PROFILE_PAGE ="HIDE_PROFILE_PAGE";

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const SHOW_COMMON_SUCCESS_TOAST = 'SHOW_COMMON_SUCCESS_TOAST';
export const HIDE_COMMON_SUCCESS_TOAST = 'HIDE_COMMON_SUCCESS_TOAST';

export const SHOW_POPUP = 'SHOW_POPUP';
export const HIDE_POPUP = 'HIDE_POPUP';
export const SEND_OTP = 'SEND_OTP';