export const FETCH_AGENTS_REQUEST = 'FETCH_AGENTS_REQUEST';
export const FETCH_AGENTS_SUCCESS = 'FETCH_AGENTS_SUCCESS';
export const FETCH_AGENTS_FAILURE = 'FETCH_AGENTS_FAILURE';

export const FETCH_AGENT_REQUEST = 'FETCH_AGENT_REQUEST';
export const FETCH_AGENT_SUCCESS = 'FETCH_AGENT_SUCCESS';
export const FETCH_AGENT_FAILURE = 'FETCH_AGENT_FAILURE';

export const SHOW_CREATE_AGENT_SIDEBAR = 'SHOW_CREATE_AGENT_SIDEBAR ';
export const HIDE_CREATE_AGENT_SIDEBAR = 'HIDE_CREATE_AGENT_SIDEBAR';

export const SHOW_EDIT_AGENT_SIDEBAR = 'SHOW_EDIT_AGENT_SIDEBAR';
export const HIDE_EDIT_AGENT_SIDEBAR = 'HIDE_EDIT_AGENT_SIDEBAR';


export const SHOW_MINI_SIDEBAR   = 'SHOW_MINI_SIDEBAR';
export const HIDE_MINI_SIDEBAR   = 'HIDE_MINI_SIDEBAR';

export const SHOW_FEEDBACK_FORM   = 'SHOW_FEEDBACK_FORM';
export const HIDE_FEEDBACK_FORM   = 'HIDE_FEEDBACK_FORM';

export const SHOW_AGENT_SUCCESS_TOAST = 'SHOW_AGENT_SUCCESS_TOAST';
export const HIDE_AGENT_SUCCESS_TOAST = 'HIDE_AGENT_SUCCESS_TOAST';

export const SHOW_FEEDBACK_SUCCESS_TOAST = 'SHOW_FEEDBACK_SUCCESS_TOAST';
export const HIDE_FEEDBACK_SUCCESS_TOAST = 'HIDE_FEEDBACK_SUCCESS_TOAST';

export const SHOW_AGENT_DELETE_SCREEN = 'SHOW_AGENT_DELETE_SCREEN';
export const HIDE_AGENT_DELETE_SCREEN = 'HIDE_AGENT_DELETE_SCREEN';

export const UPDATE_AGENT_REQUEST = 'UPDATE_AGENT_REQUEST';
export const UPDATE_AGENT_SUCCESS = 'UPDATE_AGENT_SUCCESS';
export const UPDATE_AGENT_FAILURE = 'UPDATE_AGENT_FAILURE';


export const FETCH_AGENT_SIDEBAR_DATA_REQUEST = 'FETCH_AGENT_SIDEBAR_DATA_REQUEST';
export const FETCH_AGENT_SIDEBAR_DATA_SUCCESS = 'FETCH_AGENT_SIDEBAR_DATA_SUCCESS';
export const FETCH_AGENT_SIDEBAR_DATA_FAILURE = 'FETCH_AGENT_SIDEBAR_DATA_FAILURE';

export const CREATE_AGENT_REQUEST = 'CREATE_AGENT_REQUEST';
export const CREATE_AGENT_SUCCESS = 'CREATE_AGENT_SUCCESS';
export const CREATE_AGENT_FAILURE = 'CREATE_AGENT_FAILURE';

export const CREATE_FEEDBACK_REQUEST = 'CREATE_FEEDBACK_REQUEST';
export const CREATE_FEEDBACK_SUCCESS = 'CREATE_FEEDBACK_SUCCESS';
export const CREATE_FEEDBACK_FAILURE = 'CREATE_FEEDBACK_FAILURE';

export const DELETE_AGENTS_REQUEST = 'DELETE_AGENTS_REQUEST';
export const DELETE_AGENTS_SUCCESS = 'DELETE_AGENTS_SUCCESS';
export const DELETE_AGENTS_FAILURE = 'DELETE_AGENTS_FAILURE';



export const SEARCH_AGENT_REQUEST = 'SEARCH_AGENT_REQUEST';
export const SEARCH_AGENT_SUCCESS = 'SEARCH_AGENT_SUCCESS';
export const SEARCH_AGENT_FAILURE = 'SEARCH_AGENT_FAILURE';

export const FETCH_ROLE_REQUEST = 'FETCH_ROLE_REQUEST';
export const FETCH_ROLE_SUCCESS = 'FETCH_ROLE_SUCCESS';
export const FETCH_ROLE_FAILURE = 'FETCH_ROLE_FAILURE';


export const CHECK_AGENT_EMAIL_REQUEST = 'CHECK_AGENT_EMAIL_REQUEST';
export const CHECK_AGENT_EMAIL_SUCCESS = 'CHECK_AGENT_EMAIL_SUCCESS';
export const CHECK_AGENT_EMAIL_FAILURE = 'CHECK_AGENT_EMAIL_FAILURE';

export const RESET_AGENT_EMAIL = 'RESET_AGENT_EMAIL';

export const SET_EMPTY_AGENT_SEARCH="SET_EMPTY_AGENT_SEARCH";
export const RESET_EMPTY_AGENT_SEARCH="RESET_EMPTY_AGENT_SEARCH";

export const SHOW_SEARCH_BACK_BUTTON ="SHOW_SEARCH_BACK_BUTTON";
export const HIDE_SEARCH_BACK_BUTTON ="HIDE_SEARCH_BACK_BUTTON";



