export const FETCH_PREVIEW_ARTICLE_REQUEST = 'FETCH_PREVIEW_ARTICLE_REQUEST';

export const FETCH_PREVIEW_ARTICLE_SUCCESS = 'FETCH_PREVIEW_ARTICLE_SUCCESS';

export const FETCH_PREVIEW_ARTICLE_FAILURE = 'FETCH_PREVIEW_ARTICLE_FAILURE';