export const FETCH_DEPARTMENTS_REQUEST = 'FETCH_DEPARTMENTS_REQUEST';
export const FETCH_DEPARTMENTS_SUCCESS = 'FETCH_DEPARTMENTS_SUCCESS';
export const FETCH_DEPARTMENTS_FAILURE = 'FETCH_DEPARTMENTS_FAILURE';

export const SHOW_CREATE_DEPARTMENT_SIDEBAR   = 'SHOW_CREATE_DEPARTMENT_SIDEBAR';
export const HIDE_CREATE_DEPARTMENT_SIDEBAR   = 'HIDE_CREATE_DEPARTMENT_SIDEBAR';

export const SHOW_EDIT_DEPARTMENT_SIDEBAR   = 'SHOW_EDIT_DEPARTMENT_SIDEBAR';
export const HIDE_EDIT_DEPARTMENT_SIDEBAR   = 'HIDE_EDIT_DEPARTMENT_SIDEBAR';

export const SHOW_DEPARTMENT_SUCCESS_TOAST = 'SHOW_DEPARTMENT_SUCCESS_TOAST';
export const HIDE_DEPARTMENT_SUCCESS_TOAST = 'HIDE_DEPARTMENT_SUCCESS_TOAST';

export const SHOW_DEPARTMENT_DELETE_SCREEN = 'SHOW_DEPARTMENT_DELETE_SCREEN';
export const HIDE_DEPARTMENT_DELETE_SCREEN = 'HIDE_DEPARTMENT_DELETE_SCREEN';

export const FETCH_AGENT_SUBSTRING_REQUEST = 'FETCH_AGENT_SUBSTRING_REQUEST';
export const FETCH_AGENT_SUBSTRING_SUCCESS = 'FETCH_AGENT_SUBSTRING_SUCCESS';
export const FETCH_AGENT_SUBSTRING_FAILURE = 'FETCH_AGENT_SUBSTRING_FAILURE';

export const DELETE_DEPARTMENTS_REQUEST = 'DELETE_DEPARTMENTS_REQUEST';
export const DELETE_DEPARTMENTS_SUCCESS = 'DELETE_DEPARTMENTS_SUCCESS';
export const DELETE_DEPARTMENTS_FAILURE = 'DELETE_DEPARTMENTS_FAILURE';


export const FETCH_DEPARTMENT_REQUEST = 'FETCH_DEPARTMENT_REQUEST';
export const FETCH_DEPARTMENT_SUCCESS = 'FETCH_DEPARTMENT_SUCCESS';
export const FETCH_DEPARTMENT_FAILURE = 'FETCH_DEPARTMENT_FAILURE';

export const CREATE_DEPARTMENT_REQUEST = 'CREATE_DEPARTMENT_REQUEST';
export const CREATE_DEPARTMENT_SUCCESS = 'CREATE_DEPARTMENT_SUCCESS';
export const CREATE_DEPARTMENT_FAILURE = 'CREATE_DEPARTMENT_FAILURE';

export const UPDATE_DEPARTMENT_REQUEST = 'UPDATE_DEPARTMENT_REQUEST';
export const UPDATE_DEPARTMENT_SUCCESS = 'UPDATE_DEPARTMENT_SUCCESS';
export const UPDATE_DEPARTMENT_FAILURE = 'UPDATE_DEPARTMENT_FAILURE';

export const CHECK_DEPARTMENT_NAME_REQUEST = 'CHECK_DEPARTMENT_NAME_REQUEST';
export const CHECK_DEPARTMENT_NAME_SUCCESS = 'CHECK_DEPARTMENT_NAME_SUCCESS';
export const CHECK_DEPARTMENT_NAME_FAILURE = 'CHECK_DEPARTMENT_NAME_FAILURE';

export const RESET_DEPARTMENT_NAME = 'RESET_DEPARTMENT_NAME';