// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:608c0677-53cc-4094-bcab-ad0dfdda9709",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_2peWKUP9P",
    "aws_user_pools_web_client_id": "6nkq3rphk4gae0dchcnfvtpmdj",
    "oauth": {
        "domain": "auths.auth.us-west-2.amazoncognito.com",
        "scope": [
            "email",
            "openid",
            "aws.cognito.signin.user.admin",
            "profile"
        ],
        "redirectSignIn": "https://www.appypiedesk.com/admin/signup",
        "redirectSignOut": "https://www.appypiedesk.com/admin",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
