export const FETCH_ROLES_REQUEST = 'FETCH_ROLES_REQUEST';
export const FETCH_ROLES_SUCCESS = 'FETCH_ROLES_SUCCESS';
export const FETCH_ROLES_FAILURE = 'FETCH_ROLES_FAILURE';

export const SHOW_CREATE_ROLE_SIDEBAR   = 'SHOW_CREATE_ROLE_SIDEBAR';
export const HIDE_CREATE_ROLE_SIDEBAR   = 'HIDE_CREATE_ROLE_SIDEBAR';

export const SHOW_EDIT_ROLE_SIDEBAR   = 'SHOW_EDIT_ROLE_SIDEBAR';
export const HIDE_EDIT_ROLE_SIDEBAR   = 'HIDE_EDIT_ROLE_SIDEBAR';

export const SHOW_ROLE_SUCCESS_TOAST = 'SHOW_ROLE_SUCCESS_TOAST';
export const HIDE_ROLE_SUCCESS_TOAST = 'HIDE_ROLE_SUCCESS_TOAST';

export const SHOW_ROLE_DELETE_SCREEN = 'SHOW_ROLE_DELETE_SCREEN';
export const HIDE_ROLE_DELETE_SCREEN = 'HIDE_ROLE_DELETE_SCREEN';

export const FETCH_ROLE_REQUEST = 'FETCH_ROLE_REQUEST';
export const FETCH_ROLE_SUCCESS = 'FETCH_ROLE_SUCCESS';
export const FETCH_ROLE_FAILURE = 'FETCH_ROLE_FAILURE';


export const CREATE_ROLE_REQUEST = 'CREATE_ROLE_REQUEST';
export const CREATE_ROLE_SUCCESS = 'CREATE_ROLE_SUCCESS';
export const CREATE_ROLE_FAILURE = 'CREATE_ROLE_FAILURE';

export const DELETE_ROLES_REQUEST = 'DELETE_ROLES_REQUEST';
export const DELETE_ROLES_SUCCESS = 'DELETE_ROLES_SUCCESS';
export const DELETE_ROLES_FAILURE = 'DELETE_ROLES_FAILURE';


export const UPDATE_ROLE_REQUEST = 'UPDATE_ROLE_REQUEST';
export const UPDATE_ROLE_SUCCESS = 'UPDATE_ROLE_SUCCESS';
export const UPDATE_ROLE_FAILURE = 'UPDATE_ROLE_FAILURE';

export const CHECK_ROLE_NAME_REQUEST = 'CHECK_ROLE_NAME_REQUEST';
export const CHECK_ROLE_NAME_SUCCESS = 'CHECK_ROLE_NAME_SUCCESS';
export const CHECK_ROLE_NAME_FAILURE = 'CHECK_ROLE_NAME_FAILURE';

export const RESET_ROLE_NAME = 'RESET_ROLE_NAME';

export const CREATE_GENERAL_DATA = 'CREATE_GENERAL_DATA';